build node in parellel [ci skip]

diff --git a/vxvm b/vxvm
--- a/vxvm
+++ b/vxvm
@@ -1,23 +1,27 @@
 #!/bin/bash
 
 set -e
-set -x
 
-lang=$1
-version=$2
+#
 pkg_prefix="vx-packages-"
-pkg_packages="/dists/trusty/main/binary-amd64/Packages.gz"
-pkg_host=${PKG_HOST:-http://trusty.pkg.vexor.io}
-regexp=$(perl -e "print(quotemeta('${pkg_prefix}${lang}-${version}'))")
+pkg_metadata="/dists/trusty/main/binary-amd64/Packages.gz"
+pkg_host=${PKG_HOST:-http://mirror.pkg.vexor.io}
+pkg_install_path="/opt/vexor/packages"
+
+#
 awk=${AWK:-awk}
 
+#
 curl="curl --fail --silent --show-error"
+mktemp="mktemp"
 
-usage () {
-  cat <<EOF
-  Usage vxvm <lang> <version>
-EOF
-  exit 1
+# forward reclaration
+package_path=""
+package_name=""
+
+
+function sedeasy {
+  sed -i "s/$(echo $1 | sed -e 's/\([[\/.*]\|\]\)/\\&/g')/$(echo $2 | sed -e 's/[\/&]/\\&/g')/g"
 }
 
 echoerr() {
@@ -25,64 +29,117 @@ echoerr() {
 }
 
 silent_output () {
-  cmd=$@
+  local cmd=$@
+  local log=$($mktemp)
 
-  log=$(mktemp -t vx)
+  local rs=$( ( $cmd > $log 2> $log && echo "ok" ) || echo "fail" )
 
-  $cmd > $log 2> $log || (
+  if [ "$rs" = "fail" ] ; then
     echoerr "failed: $cmd"
     echoerr ""
     cat $log
     rm $log
     exit 1
-  )
-
-  rm -f $log
+  fi
 }
 
-test "x$lang" = "x" && usage
-test "x$version" = "x" && usage
+vxvm_search_in_repo () {
+  local lang=$1
+  local version=$2
+  local regexp="${pkg_prefix}${lang}-${version}"
 
-# download metadata
-metadata=$(mktemp -t vx)
-$curl $pkg_host/$pkg_packages | gunzip | \
-  $awk '/Package/{ print $2} ; /Filename/ { print $2 }' | \
-  xargs -n2 \
-  > $metadata
+  # download metadata
+  metadata=$($mktemp)
+  $curl $pkg_host/$pkg_metadata | gunzip | \
+    $awk '/Package/{ print $2} ; /Filename/ { print $2 }' | \
+    xargs -n2 \
+    > $metadata
 
-# strict match
-package_url=$(cat $metadata | $awk -v ref="^$regexp " 'match($0, ref){ print $2 }' | head -n1)
-package_version=$(cat $metadata | $awk -v ref="^$regexp " 'match($0, ref){ print $1 }' | head -n1)
+  # strict match
+  package_path=$(cat $metadata | $awk -v ref="$regexp " 'match($0, ref){ print $2 }' | head -n1)
+  package_name=$(cat $metadata | $awk -v ref="$regexp " 'match($0, ref){ print $1 }' | head -n1)
 
-if [ "x$package_name" = "x" ] ; then
-  # fuzzy match
-  package_url=$(cat $metadata | sort -r | $awk -v ref="^$regexp" 'match($0, ref){ print $2}' | head -n1)
-  package_version=$(cat $metadata | sort -r | $awk -v ref="^$regexp" 'match($0, ref){ print $1}' | head -n1)
-fi
+  if [ "x$package_name" = "x" ] ; then
+    # fuzzy match
+    package_path=$(cat $metadata | sort -r | $awk -v ref="$regexp" 'match($0, ref){ print $2}' | head -n1)
+    package_name=$(cat $metadata | sort -r | $awk -v ref="$regexp" 'match($0, ref){ print $1}' | head -n1)
+  fi
 
-rm $metadata
+  rm $metadata
+}
 
-if [ "x$package_url" = "x" ] ; then
-  echoerr "cannot found $lang ($version)"
+vxvm_extract_id () {
+  echo  $package_name | sed -e "s/${pkg_prefix}//g"
+}
+
+vxvm_valid_package_url () {
+  if [ "x$package_path" = "x" ] ; then
+    echoerr "cannot found $lang ($version)"
+    exit 1
+  fi
+}
+
+vxvm_usage () {
+  cat <<EOF
+  Usage vxvm $1 <lang> <version>
+EOF
   exit 1
-fi
+}
 
-# download package
-package_install_path=/opt/vexor/packages/${package_version}
+vxvm_search () {
+  local lang=$1
+  local version=$2
 
-if [ -d $package_install_path ] ; then
-  echoerr "Using $package_version"
-fi
+  test "x$lang" = "x" && vxvm_usage "search"
+  test "x$version" = "x" && vxvm_usage "search"
 
-if [ ! -d $package_install_path ] ; then
-  package_file=$(basename $package_name)
-  package_tmp_dir=$(mktemp -d -t vx)
-  package_tmp_file=$package_tmp_dir/$package_file
+  vxvm_search_in_repo $lang $version
+  vxvm_valid_package_url
 
-  echoerr "download and install $package_version"
-  $curl $pkg_host/$package_url > $package_tmp_file
-  silent_output dpkg -i $package_tmp_file
-  rm -rf $package_tmp_dir
-fi
+  echo "Version:  $(vxvm_extract_id)"
+  echo "Location: $pkg_host/${package_url}"
+  echo "Install:  ${pkg_install_path}/$(vxvm_extract_id)"
+}
 
-echo $package_install_path/activate
+vxvm_install () {
+  local lang=$1
+  local version=$2
+
+  test "x$lang" = "x" && vxvm_usage "install"
+  test "x$version" = "x" && vxvm_usage "install"
+
+  vxvm_search_in_repo $lang $version
+  vxvm_valid_package_url
+
+  local id=$(vxvm_extract_id)
+
+  test -d $pkg_install_path/$id && (
+    echoerr "Using $id"
+    exit 0
+  )
+
+  if [ ! -d $pkg_install_path/$id ] ; then
+    local tmp_dir=$($mktemp -d)
+    local tmp_file=$tmp_dir/$package_name
+
+    echoerr "download and install $id"
+    $curl $pkg_host/$package_path > $tmp_file
+    silent_output dpkg -i $tmp_file
+    rm -rf $tmp_dir
+  fi
+
+  echo $pkg_install_path/$id/activate
+}
+
+case $1 in
+  search)
+    vxvm_search $2 $3
+    ;;
+  install)
+    vxvm_install $2 $3
+    ;;
+  *)
+    echo "Usage vxvm (search|install)"
+    ;;
+esac
+
